apiVersion: v1
kind: Service
metadata:
  name: {{ include "farm-proxy.fullname" . }}
  labels:
    {{- include "farm-proxy.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports: {{- toYaml .Values.service.ports | nindent 4 }}
  selector:
    {{- include "farm-proxy.selectorLabels" . | nindent 4 }}
